### ISSUE TITLE
Swap connection statistics graphs for single graph showing boolean of "connected" or "unconnected"

### ISSUE THREAD

**Issue by cortadocodes** [aerosense-ai/aerosense-dashboard#15]
Transform `filtered_rssi` or `tx_power` to a boolean of `connected` or `unconnected` to show as minute-wise aggregated connection statistics.

**Comment by time-trader** [comment]
After giving this a little more thought, I just realised we don't need to look into   `filtered_rssi` or `tx_power ` . What we need is an aggregation by `sensor_type_reference`. So in this case when `connection-statistics` type is received.

Thinking about it further, what we can have visually is a drop down list for all senor_types, and when chosen,  display a "calendar" of "data availability".  Starting with day granularity (i.e. if the day is green, means we sampled that type of data ) and then by clicking on a specific day we can minute level granularity...

**Comment by time-trader** [comment]
Now, if this type of aggregation should be performed daily, with the results stored somewhere else, is a different question.

**Comment by time-trader** [comment]
Sample query:
```
SELECT EXTRACT(DAY FROM datetime) as day_of_month, sensor_type_reference, 
COUNT(*) AS number_of_samples
FROM `aerosense-twined.greta.sensor_data` 
WHERE 
node_id="2" and
EXTRACT(YEAR FROM datetime) = 2022 and
EXTRACT(MONTH FROM datetime) = 7
GROUP BY Day, sensor_type_reference
ORDER BY Day ASC
```

**Comment by time-trader** [comment]
It seems the feature is not very useful and partially covered after introduction "measurement campaign" table.
See https://github.com/aerosense-ai/data-gateway/issues/107
