### ISSUE TITLE
Plot pre-processed data

### ISSUE THREAD

**Issue by time-trader** [aerosense-ai/aerosense-dashboard#17]
Pre process data with `RawSignal` class methods in `aerosense-tools`:

- Pad gaps
- Convert to variable (Closes #9 )

Maybe by introducing a pre-process check-box in the dashboard?
After pre-processing, plot data with sensor specific layout using `RawSignal.plot(metadata)`

**Comment by cortadocodes** [comment]
Is this related to https://github.com/aerosense-ai/aerosense-tools/pull/13 ?

**Comment by time-trader** [comment]
Closed with #24
